# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "zstd-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"
zstd = "0.13.1"
# zstd = "0.13.1"

[features]
zstd = []
# [dependencies]
# zstd = "0.13.1"
# cargo build --target wasm32-unknown-unknown --no-default-features
